services:
  app:
    build: .
    image: go_weather:latest
    container_name: go_weather_app
    environment:
      - PORT=8080
      - GRPC_PORT=9090
      # - API_KEY=ultrasecretkey123  # (optional) enable API key middleware
    ports:
      - "8081:8080"
      - "9091:9090"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"
    depends_on:
      - app

  # grafana (optional)
  # grafana:
  #   image: grafana/grafana-oss:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin